import { GroceryItem } from '../types/grocery';

const now = Date.now();
const days = (n: number) => new Date(now + n * 86400000);

export const MOCK_ITEMS: GroceryItem[] = [
  // --- Protein (3 items) ---
  {
    id: '1',
    name: 'Chicken breast',
    category: 'protein',
    barcode: '075278310419',
    storageLocation: 'fridge',
    storageHistory: [{ eventType: 'added', location: 'fridge', date: days(-3) }],
    printedExpirationDate: days(0),
    effectiveExpirationDate: days(0),
    expirationDateType: 'freeze_or_use_by',
    isFreezable: true,
    thawCycleCount: 0,
    unitOfMeasure: 'lbs',
    originalQuantity: 1.5,
    remainingQuantity: 1.5,
    purchaseDate: days(-3),
    dateAdded: days(-3),
    store: 'Whole Foods',
    unitCost: 8.99,
    totalCost: 13.49,
    inputMethod: 'barcode',
  },
  {
    id: '2',
    name: 'Ground turkey',
    category: 'protein',
    storageLocation: 'fridge',
    storageHistory: [{ eventType: 'added', location: 'fridge', date: days(-1) }],
    effectiveExpirationDate: days(62),
    expirationDateType: 'use_by',
    isFreezable: true,
    thawCycleCount: 0,
    unitOfMeasure: 'lbs',
    originalQuantity: 1,
    remainingQuantity: 1,
    purchaseDate: days(-1),
    dateAdded: days(-1),
    store: 'Whole Foods',
    inputMethod: 'barcode',
  },
  {
    id: '3',
    name: 'Eggs',
    category: 'protein',
    storageLocation: 'fridge',
    storageHistory: [{ eventType: 'added', location: 'fridge', date: days(-5) }],
    effectiveExpirationDate: days(18),
    expirationDateType: 'best_by',
    isFreezable: false,
    thawCycleCount: 0,
    unitOfMeasure: 'units',
    originalQuantity: 12,
    remainingQuantity: 9,
    purchaseDate: days(-5),
    dateAdded: days(-5),
    store: 'Trader Joe\'s',
    inputMethod: 'barcode',
  },

  // --- Produce (4 items) ---
  {
    id: '4',
    name: 'Spinach',
    category: 'produce',
    storageLocation: 'fridge',
    storageHistory: [{ eventType: 'added', location: 'fridge', date: days(-5) }],
    effectiveExpirationDate: days(2),
    expirationDateType: 'estimated',
    isFreezable: true,
    thawCycleCount: 0,
    unitOfMeasure: 'oz',
    originalQuantity: 5,
    remainingQuantity: 4,
    purchaseDate: days(-5),
    dateAdded: days(-5),
    store: 'Whole Foods',
    inputMethod: 'image_recognition',
  },
  {
    id: '5',
    name: 'Bell pepper',
    category: 'produce',
    storageLocation: 'fridge',
    storageHistory: [{ eventType: 'added', location: 'fridge', date: days(-4) }],
    effectiveExpirationDate: days(2),
    expirationDateType: 'estimated',
    isFreezable: true,
    thawCycleCount: 0,
    unitOfMeasure: 'units',
    originalQuantity: 3,
    remainingQuantity: 3,
    purchaseDate: days(-4),
    dateAdded: days(-4),
    store: 'Whole Foods',
    inputMethod: 'image_recognition',
  },
  {
    id: '6',
    name: 'Bananas',
    category: 'produce',
    storageLocation: 'pantry',
    storageHistory: [{ eventType: 'added', location: 'pantry', date: days(-2) }],
    effectiveExpirationDate: days(5),
    expirationDateType: 'estimated',
    isFreezable: true,
    thawCycleCount: 0,
    unitOfMeasure: 'units',
    originalQuantity: 6,
    remainingQuantity: 5,
    purchaseDate: days(-2),
    dateAdded: days(-2),
    store: 'Trader Joe\'s',
    inputMethod: 'image_recognition',
  },
  {
    id: '7',
    name: 'Carrots',
    category: 'produce',
    storageLocation: 'fridge',
    storageHistory: [{ eventType: 'added', location: 'fridge', date: days(-1) }],
    effectiveExpirationDate: days(14),
    expirationDateType: 'estimated',
    isFreezable: true,
    thawCycleCount: 0,
    unitOfMeasure: 'lbs',
    originalQuantity: 1,
    remainingQuantity: 1,
    purchaseDate: days(-1),
    dateAdded: days(-1),
    store: 'Whole Foods',
    inputMethod: 'image_recognition',
  },

  // --- Dairy (2 items) ---
  {
    id: '8',
    name: 'Greek yogurt',
    category: 'dairy',
    storageLocation: 'fridge',
    storageHistory: [{ eventType: 'added', location: 'fridge', date: days(-2) }],
    effectiveExpirationDate: days(5),
    expirationDateType: 'use_by',
    isFreezable: false,
    thawCycleCount: 0,
    unitOfMeasure: 'oz',
    originalQuantity: 32,
    remainingQuantity: 32,
    purchaseDate: days(-2),
    dateAdded: days(-2),
    store: 'Whole Foods',
    inputMethod: 'barcode',
  },
  {
    id: '9',
    name: 'Whole milk',
    category: 'dairy',
    storageLocation: 'fridge',
    storageHistory: [{ eventType: 'added', location: 'fridge', date: days(-3) }],
    effectiveExpirationDate: days(10),
    expirationDateType: 'sell_by',
    isFreezable: false,
    thawCycleCount: 0,
    unitOfMeasure: 'oz',
    originalQuantity: 64,
    remainingQuantity: 48,
    purchaseDate: days(-3),
    dateAdded: days(-3),
    store: 'Trader Joe\'s',
    inputMethod: 'barcode',
  },

  // --- Grains (1 item) ---
  {
    id: '10',
    name: 'Brown rice',
    category: 'grains',
    storageLocation: 'pantry',
    storageHistory: [{ eventType: 'added', location: 'pantry', date: days(-14) }],
    effectiveExpirationDate: days(180),
    expirationDateType: 'best_by',
    isFreezable: false,
    thawCycleCount: 0,
    unitOfMeasure: 'lbs',
    originalQuantity: 2,
    remainingQuantity: 1.5,
    purchaseDate: days(-14),
    dateAdded: days(-14),
    store: 'Whole Foods',
    inputMethod: 'barcode',
  },
];

// Items expiring today or tomorrow (for Home screen Needs Attention section)
export const MOCK_URGENT_ITEMS = MOCK_ITEMS.filter((item) => {
  const d = Math.ceil(
    (item.effectiveExpirationDate.getTime() - Date.now()) / 86400000
  );
  return d <= 1;
});

// Items expiring this week (for "See all" link)
export const MOCK_EXPIRING_THIS_WEEK = MOCK_ITEMS.filter((item) => {
  const d = Math.ceil(
    (item.effectiveExpirationDate.getTime() - Date.now()) / 86400000
  );
  return d <= 7;
});

export const MOCK_STATS = {
  foodScore: 84,
  streak: 14,
  savedThisMonth: 47,
  projectedMonthEnd: 98,
  daysElapsed: 14,
  daysInMonth: 31,
  totalItems: MOCK_ITEMS.length,
  expiringThisWeek: MOCK_EXPIRING_THIS_WEEK.length,
};
